modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Softer%20Hay%20Bales"
logoFile="icon.png"

[[mods]]
modId="softerhaybales"
version="3.0"
displayName="Softer Hay Bales"
displayURL="https://curseforge.com/minecraft/mc-mods/softer-hay-bales"
authors="Rick South"
description='''Makes hay bales negate fall damage entirely, Assassin's Creed style.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.softerhaybales]]
    modId="collective"
    mandatory=true
    versionRange="[6.7,)"
    ordering="NONE"
    side="BOTH"